name: rebecca_ptm_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.7.0
  - aom=3.12.1
  - appdirs=1.4.4
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.2
  - biopython=1.85
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - bs4=4.14.2
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cd-hit=4.8.1
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - docker-pycreds=0.4.0
  - eval_type_backport=0.3.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - gitdb=4.0.12
  - gitpython=3.1.46
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - joblib=1.5.3
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20260107.0
  - libavif=1.3.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libmpdec=4.0.0
  - libopenjpeg=2.5.4
  - libpng=1.6.54
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib-base=3.10.8
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy=2.4.1
  - numpy-base=2.4.1
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - protobuf=6.33.4
  - psutil=7.2.1
  - pthread-stubs=0.3
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pyparsing=3.3.1
  - pysocks=1.7.1
  - python=3.14.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python_abi=3.14
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - readline=8.3
  - requests=2.32.5
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - sentry-sdk=2.49.0
  - setproctitle=1.3.7
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - soupsieve=2.5
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - typing=3.10.0.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - venn=0.1.3
  - wandb=0.23.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
